version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-spring
    environment:
      MONGO_INITDB_ROOT_USERNAME: spring
      MONGO_INITDB_ROOT_PASSWORD: spring
    ports:
        - 8001:27017